name: Build and push Docker images

on:
  push:

jobs:
  docker:
    runs-on: koyeb-runner-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.bundled_model
          tags: koyeb/bundled/meta-llama/Llama-3.1-8B:latest
          build-args: |
            MODEL_NAME=meta-llama/Llama-3.1-8B
            HF_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
