name: Build and push Docker images

on:
  push:

jobs:
  docker:
    runs-on: koyeb-runner
    strategy:
      matrix:
        model:
          - name: meta-llama/Llama-3.1-8B
            tag: koyeb/meta-llama-3.1-8b:latest
          - name: NousResearch/Hermes-3-Llama-3.1-8B
            tag: koyeb/nousresearch-hermes-3-llama-3.1-8b:latest
          - name: mistralai/Mistral-7B-Instruct-v0.3
            tag: koyeb/mistralai-mistral-7b-instruct-v0.3:latest
          - name: google/gemma-2-9b-it
            tag: koyeb/google-gemma-2-9b-it:latest
          - name: Qwen/Qwen2.5-7B-Instruct
            tag: koyeb/qwen-qwen2.5-7b-instruct:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile.bundled_model
          tags: ${{ matrix.model.tag }}
          outputs: |
            type=registry,compression=zstd
          build-args: |
            MODEL_NAME=${{ matrix.model.name }}
            HF_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
